### ISSUE TITLE
Fler grundläggande räknetal.

### ISSUE THREAD

**Issue by mattiasvillani** [StatisticsSU/SDA1#10]
Vissa studenter har svårt för att räkna medelvärden. Summor etc. Skapa några enklare övningar som kompletterar bokens tal.

**Comment by Ev16** [comment]
Är på gång, planerar att göra fler praktiska räkneövningar som kan användas den här terminen och nästkommande.

**Comment by mattiasvillani** [comment]
Stänger denna eftersom Mona har gjort tillräckligt här.
